title:            NecroBot2
description:      "The opensource c# pokemon go bot"
logo:             necrobot2.jpg
disqus_shortname: necrobot2com
share:            true
dropcap:	   true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	 http://necrobot2.com

# Owner/author information
owner:
  name:           Necrobot2 Team
  avatar:         Necrobot2.jpg
  email:          Necrobot2Team@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Programming is 1% knowledge, 2% ability and 97% getting the ability to work with the knowledge :)
  # Social networking links used in footer. Update and remove as you like.
  twitter:        Necrobot2Team
  facebook:       Necrobot2Team
  github:         Necrobot2Team    
  instagram:      Necrobot2Team
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/+Necrobot2Team

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-46791108-110
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Snipe
    url: http://snipe.necrobot2.com
    external: true
#  - title: MSniper
#    url: https://www.msniper.com
#    external: true  
  - title: Documents
    url: /documents
  - title: Downloads
    url: http://necrobot2.com/documents/#Releases
    external: false
  - title: About
    url: /about
  - title: Donate
    url: /donate

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Calcutta
future:      true
rouge: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   pretty

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    line_numbers: 
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

gems:
- jemoji
- jekyll-paginate
